package com.evertecinc.athmovil.sdk.checkout.objects.payment

import com.evertecinc.athmovil.sdk.checkout.objects.Items
import com.google.gson.annotations.SerializedName

class PaymentRequest {

    @SerializedName("env")
    var env: String? = null

    @SerializedName("publicToken")
    var pubToken: String? = null

    @SerializedName("timeout")
    var timeout: Long = 0

    @SerializedName("total")
    var total: Double? = null

    @SerializedName("tax")
    var tax: Double? = null

    @SerializedName("subtotal")
    var subtotal: Double? = null

    @SerializedName("metadata1")
    var metadata1: String? = null

    @SerializedName("metadata2")
    var metadata2: String? = null

    @SerializedName("items")
    var items: List<Items>? = null

    @SerializedName("phoneNumber")
    var phoNumber: String? = null

    @SerializedName("ecommerceId")
    var ecommerceId: String? = null

    constructor()

    constructor(
        env: String?,
        publicToken: String?,
        timeout: Long,
        total: Double?,
        tax: Double?,
        subtotal: Double?,
        metadata1: String?,
        metadata2: String?,
        items: List<Items>?,
        phoNumber: String?
    ) {
        this.env = env
        this.pubToken = publicToken
        this.timeout = timeout
        this.total = total
        this.tax = tax
        this.subtotal = subtotal
        this.metadata1 = metadata1
        this.metadata2 = metadata2
        this.items = items
        this.phoNumber = phoNumber
    }

    // Properties for Java compatibility (getters/setters are generated by Kotlin)
    var publicToken: String?
        get() = pubToken
        set(value) {
            pubToken = value
        }

    var phoneNumber: String?
        get() = phoNumber
        set(value) {
            phoNumber = value
        }
}
